version: "3.3"
services:
  nginx:
    build: ./requirements/Nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
       - wordpress
  wordpress:
    build: ./requirements/Wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception
    volumes: 
      - wp:/var/www/html
    env_file:
    - .env
    depends_on:
        - mariadb
  mariadb:
    build: ./requirements/MariaDB
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    restart: always
    env_file:
      - .env
networks:
  inception:
volumes:
  wp:
    driver: local
    driver_opts:
      device: /home/fbouanan/data/wordpress
      o: bind
      type: bind
  db:
    driver: local
    driver_opts:
      device: /home/fbouanan/data/database
      o: bind
      type: bind
